# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/study/course_design2019/CDE/soc_axi_func/run_vivado/mycpu_prj1/mycpu.cache/wt [current_project]
set_property parent.project_path F:/study/course_design2019/CDE/soc_axi_func/run_vivado/mycpu_prj1/mycpu.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
set_property include_dirs F:/study/course_design2019/CDE/cpu/include [current_fileset]
add_files F:/study/course_design2019/CDE/soft/func/obj/inst_ram.coe
read_verilog {
  F:/study/course_design2019/CDE/cpu/include/sim.v
  F:/study/course_design2019/CDE/cpu/include/segpos.v
  F:/study/course_design2019/CDE/cpu/include/pcdef.v
  F:/study/course_design2019/CDE/cpu/include/opcode.v
  F:/study/course_design2019/CDE/cpu/include/funct.v
  F:/study/course_design2019/CDE/cpu/include/debug.v
  F:/study/course_design2019/CDE/cpu/include/bus.v
}
set_property file_type "Verilog Header" [get_files F:/study/course_design2019/CDE/cpu/include/sim.v]
set_property is_global_include true [get_files F:/study/course_design2019/CDE/cpu/include/sim.v]
set_property file_type "Verilog Header" [get_files F:/study/course_design2019/CDE/cpu/include/segpos.v]
set_property is_global_include true [get_files F:/study/course_design2019/CDE/cpu/include/segpos.v]
set_property file_type "Verilog Header" [get_files F:/study/course_design2019/CDE/cpu/include/pcdef.v]
set_property is_global_include true [get_files F:/study/course_design2019/CDE/cpu/include/pcdef.v]
set_property file_type "Verilog Header" [get_files F:/study/course_design2019/CDE/cpu/include/opcode.v]
set_property is_global_include true [get_files F:/study/course_design2019/CDE/cpu/include/opcode.v]
set_property file_type "Verilog Header" [get_files F:/study/course_design2019/CDE/cpu/include/funct.v]
set_property is_global_include true [get_files F:/study/course_design2019/CDE/cpu/include/funct.v]
set_property file_type "Verilog Header" [get_files F:/study/course_design2019/CDE/cpu/include/debug.v]
set_property is_global_include true [get_files F:/study/course_design2019/CDE/cpu/include/debug.v]
set_property file_type "Verilog Header" [get_files F:/study/course_design2019/CDE/cpu/include/bus.v]
set_property is_global_include true [get_files F:/study/course_design2019/CDE/cpu/include/bus.v]
read_verilog -library xil_defaultlib {
  F:/study/course_design2019/CDE/cpu/bus/AXIAdapter.v
  F:/study/course_design2019/CDE/cpu/core/stage/id/BranchGen.v
  F:/study/course_design2019/CDE/cpu/core/Core.v
  F:/study/course_design2019/CDE/cpu/core/stage/ex/EX.v
  F:/study/course_design2019/CDE/cpu/core/stage/ex/EXMEM.v
  F:/study/course_design2019/CDE/cpu/core/stage/id/FunctGen.v
  F:/study/course_design2019/CDE/cpu/core/stage/id/ID.v
  F:/study/course_design2019/CDE/cpu/core/stage/id/IDEX.v
  F:/study/course_design2019/CDE/cpu/core/stage/if/IFID.v
  F:/study/course_design2019/CDE/cpu/core/stage/mem/MEM.v
  F:/study/course_design2019/CDE/cpu/core/stage/mem/MEMWB.v
  F:/study/course_design2019/CDE/cpu/core/stage/id/MemGen.v
  F:/study/course_design2019/CDE/cpu/core/stage/id/OperandGen.v
  F:/study/course_design2019/CDE/cpu/core/stage/if/PC.v
  F:/study/course_design2019/CDE/cpu/core/pipeline/PipelineController.v
  F:/study/course_design2019/CDE/cpu/core/pipeline/PipelineDeliver.v
  F:/study/course_design2019/CDE/cpu/core/storage/RegFile.v
  F:/study/course_design2019/CDE/cpu/core/stage/id/RegGen.v
  F:/study/course_design2019/CDE/cpu/core/storage/RegReadProxy.v
  F:/study/course_design2019/CDE/cpu/mmu/StaticMMU.v
  F:/study/course_design2019/CDE/cpu/TinyMIPS.v
  F:/study/course_design2019/CDE/cpu/core/stage/wb/WB.v
  F:/study/course_design2019/CDE/soc_axi_func/rtl/axi_wrap/axi_wrap.v
  F:/study/course_design2019/CDE/soc_axi_func/rtl/ram_wrap/axi_wrap_ram.v
  F:/study/course_design2019/CDE/soc_axi_func/rtl/CONFREG/confreg.v
  F:/study/course_design2019/CDE/cpu/mycpu_top.v
  F:/study/course_design2019/CDE/soc_axi_func/rtl/soc_axi_lite_top.v
}
read_ip -quiet F:/study/course_design2019/CDE/soc_axi_func/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
set_property used_in_implementation false [get_files -all f:/study/course_design2019/CDE/soc_axi_func/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_ooc.xdc]

read_ip -quiet F:/study/course_design2019/CDE/soc_axi_func/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all f:/study/course_design2019/CDE/soc_axi_func/rtl/xilinx_ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all f:/study/course_design2019/CDE/soc_axi_func/rtl/xilinx_ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all f:/study/course_design2019/CDE/soc_axi_func/rtl/xilinx_ip/clk_pll/clk_pll_ooc.xdc]

read_ip -quiet F:/study/course_design2019/CDE/soc_axi_func/rtl/xilinx_ip/axi_ram/axi_ram.xci
set_property used_in_implementation false [get_files -all f:/study/course_design2019/CDE/soc_axi_func/rtl/xilinx_ip/axi_ram/axi_ram_ooc.xdc]

read_ip -quiet F:/study/course_design2019/CDE/soc_axi_func/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter.xci
set_property used_in_synthesis false [get_files -all f:/study/course_design2019/CDE/soc_axi_func/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/study/course_design2019/CDE/soc_axi_func/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/study/course_design2019/CDE/soc_axi_func/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_ooc.xdc]

read_ip -quiet F:/study/course_design2019/CDE/cpu/ip/InternalCrossbar/InternalCrossbar.xci
set_property used_in_implementation false [get_files -all f:/study/course_design2019/CDE/cpu/ip/InternalCrossbar/InternalCrossbar_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/study/course_design2019/CDE/soc_axi_func/run_vivado/soc_lite.xdc
set_property used_in_implementation false [get_files F:/study/course_design2019/CDE/soc_axi_func/run_vivado/soc_lite.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_axi_lite_top -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_axi_lite_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_axi_lite_top_utilization_synth.rpt -pb soc_axi_lite_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
