# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/study/course_design2019/CDE/cpu/ip/InternalCrossbar/InternalCrossbar.xci
# IP: The module: 'InternalCrossbar' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/study/course_design2019/CDE/cpu/ip/InternalCrossbar/InternalCrossbar_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InternalCrossbar'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: F:/study/course_design2019/CDE/cpu/ip/InternalCrossbar/InternalCrossbar.xci
# IP: The module: 'InternalCrossbar' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/study/course_design2019/CDE/cpu/ip/InternalCrossbar/InternalCrossbar_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InternalCrossbar'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
